package com.naatalvote.domain.audit;

public enum ActionType {
  LOGIN,
  LOGOUT,
  OTP_SEND,
  OTP_VERIFY,
  CREATE_ELECTION,
  UPDATE_ELECTION,
  CREATE_CANDIDATE,
  UPDATE_CANDIDATE,
  DELETE_CANDIDATE,
  CAST_VOTE,
  FRAUD_ALERT_CREATED,
  FRAUD_ALERT_TREATED,
  SUSPENSION_RECOMMENDED,
  SUSPENSION_DECIDED,
  USER_CREATED,
  USER_DISABLED,
  USER_ROLES_UPDATED,
  AUDIT_EXPORT
}

